import './globals.css'
import { Exo } from 'next/font/google'
import Providers from '@/utils/provider'
import FooterSite from '@/components/pageLayout/SiteFooter'

const exo = Exo({ subsets: ['latin'] })

export const metadata = {
  title: 'Apify-Web',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${exo.className} bg-light dark:bg-dark`}>
          <Providers>
            {children}
          </Providers>
      </body>
    </html>
  )
}
